services:
  libftpp-dev:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: libftpp-debian13

    volumes:
      - .:/workspace

    working_dir: /workspace

    stdin_open: true
    tty: true
